### ISSUE TITLE
Updating astroplan

### ISSUE THREAD

**Issue by bmorris3** [conda-forge/astroplan-feedstock#1]
Hey @mwcraig – I've updated astroplan, and I want to make sure I'm updating the feedstock correctly. I've updated the version number [here](https://github.com/conda-forge/astroplan-feedstock/blob/master/recipe/meta.yaml#L2) – is that all there is to it?

**Comment by mwcraig** [comment]
Hi @bmorris3 -- you also need to update the sha256. The easiest way to get that is to find astroplan on the new pypi at pypi.org. Navigate to files and there should be an option to copy the sha256.

**Comment by mwcraig** [comment]
Oh, and congrats on the new release!

**Comment by bmorris3** [comment]
Thanks @mwcraig, updating the sha256 now.

**Comment by bsipocz** [comment]
Closing this as apparently you've figured this out.

**Comment by bmorris3** [comment]
Sorry I didn't close it myself @bsipocz. Thanks for the careful bookkeeping!
